
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BD.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Виды_Транспорта
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Виды_Транспорта()
    {

        this.Транспортные_маршруты = new HashSet<Транспортные_маршруты>();

    }


    public int id_ВидаТранспорта { get; set; }

    public string Вид_транспорта { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Транспортные_маршруты> Транспортные_маршруты { get; set; }

}

}
