
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BD.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Объекты
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Объекты()
    {

        this.ПользовательОбъекты = new HashSet<ПользовательОбъекты>();

    }


    public int id_объекта { get; set; }

    public string Имя_объекта { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ПользовательОбъекты> ПользовательОбъекты { get; set; }

}

}
