//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПользовательОбъекты
    {
        public int id_пользователя { get; set; }
        public int id_объекта { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<int> E { get; set; }
        public Nullable<int> D { get; set; }
    
        public virtual Объекты Объекты { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
